import Head from 'next/head'
import Hero from "@/components/hero-page/Hero";
import {getSession, useSession} from "next-auth/react";
import ProtectedHero from "@/components/hero-page/ProtectedHero";
import {GetServerSidePropsContext} from "next";
import {IUserModel} from "@/lib/util/schema";



export default function Home() {

    return (
        <>
            <Head>
                <title>Nature Buddy</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Hero/>
        </>
    )
}
